### Template ###
# [project_name] # mandatory
# repo = "https://github.com/.../..." # mandatory
# description = "A brief description of the project." # optional, but recommended
# compile_only = true # optional, set to true if you only want to compile the project without running tests
# build_system = "npm" # optional, default is "npm". Possible values: "npm", "yarn", "pnpm", "bun".

# Environment variables
# You can set environment variables for the project.
# They will be set during the compilation and testing phases.
# [beefy.env]
# TEST_ENV = "123"
# ANOTHER_ENV = "321"

[hardhat-v2]
repo = "https://github.com/antonbaliasnikov/hardhat-template"
description = "A sample Hardhat v2 project with solx support."
build_system = "bun"

[hardhat-v3]
repo = "https://github.com/antonbaliasnikov/solx-hh3"
description = "A sample Hardhat v3 project with solx support."

[openzeppelin]
repo = "https://github.com/antonbaliasnikov/openzeppelin-contracts"
description = "A library for secure smart contract development."
build_system = "pnpm"
[openzeppelin.env]
EVM_DISABLE_MEMORY_SAFE_ASM_CHECK = "true"

[zksafe]
repo = "https://github.com/antonbaliasnikov/zksafe"
description = "A Safe module for privacy of Safe transaction signing."
build_system = "pnpm"
[zksafe.env]
EVM_DISABLE_MEMORY_SAFE_ASM_CHECK = "true"

#[ens-contracts]
#repo = "https://github.com/antonbaliasnikov/ens-contracts"
#description = "The core contracts of the ENS protocol."
#build_system = "bun"
#
#[olympus]
#repo = "https://github.com/antonbaliasnikov/olympus-contracts"
#description = "A collection of contracts for Olympus DAO."
#build_system = "yarn"
#
#[synthetix]
#repo = "https://github.com/antonbaliasnikov/synthetix"
#description = "A crypto-backed synthetic asset platform."
#build_system = "npm"
