### Template ###
# [project_name] # mandatory
# repo = "https://github.com/.../..." # mandatory
# description = "A brief description of the project." # optional, but recommended
# compile_only = true # optional, set to true if you only want to compile the project without running tests

# Environment variables
# You can set environment variables for the project.
# They will be set during the compilation and testing phases.
# [beefy.env]
# TEST_ENV = "123"
# ANOTHER_ENV = "321"

[openzeppelin]
repo = "https://github.com/antonbaliasnikov/openzeppelin-contracts"
description = "A library for secure smart contract development."

