[workspace]
members = [
    "solx",
    "solx-yul",
    "solx-standard-json",
    "solx-solc",
]
resolver = "2"

[workspace.package]
authors = [
    "The Matter Labs Team <hello@matterlabs.dev>",
]
license = "GPL-3.0"
edition = "2021"
version = "0.1.0-alpha.1"
