[build]
rustflags = [
    "-W", "missing_docs",
]
incremental = true

[target.x86_64-apple-darwin]
rustflags = [
    "-W", "missing_docs",
    "-C", "link-arg=-mmacosx-version-min=11.0",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-W", "missing_docs",
    "-C", "link-arg=-mmacosx-version-min=11.0",
]

[target.aarch64-unknown-linux-musl]
linker = "rust-lld"

[profile.release]
strip = true

[env]
LLVM_SYS_170_PREFIX = { value = "./target-llvm/target-final/", relative = true, force = false }
BOOST_PREFIX = { value = "/opt/homebrew/lib/", relative = false, force = false }
SOLC_PREFIX = { value = "./era-solidity/build/", relative = false, force = false }

[tools.clippy]
warn = [
    "missing_docs_in_private_items",
]
