name: Foundry tests

on:
  workflow_dispatch:
    inputs:
      solx_candidate_branch:
        description: 'Solidity candidate branch to use. If empty, the current branch will be used.'
        required: false
        default: ''
      solx_reference_branch:
        description: 'Solidity reference branch to use. If empty, the current branch will be used.'
        required: false
        default: ''
  pull_request:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.repository_id }}-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  forge-benchmarks:
    uses: ./.github/workflows/forge-benchmarks.yaml
    secrets: inherit
    with:
      print-markdown-tables: 'true'
      upload-reports: ${{ github.event_name == 'pull_request' }}
      solx_candidate_branch: ${{ inputs.solx_candidate_branch || github.event.pull_request.head.sha }}
      solx_reference_branch: ${{ inputs.solx_reference_branch || 'main' }}
      solx-repo: ${{ github.event.pull_request.head.repo.full_name || 'matter-labs/solx' }} # required to properly test forks
